name: publish_latest
on:
  push:
    branches:
      - 'main'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker build . --tag ghcr.io/badgerloop-software/engineering-data-distributor-image:latest
          docker push ghcr.io/badgerloop-software/engineering-data-distributor-image:latest

  delete_untagged_images:
    needs: build_and_publish
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          owner: badgerloop-software
          package-name: engineering-data-distributor-image
          package-type: container
          password: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
